### ISSUE TITLE
Update Cassandra JDBC driver version

### ISSUE THREAD

**Issue by sualeh** [ing-bank/cassandra-jdbc-wrapper#19]
Cassandra JDBC driver version has not been upgraded since v4.4.0.

See [CassandraDriver](https://github.com/ing-bank/cassandra-jdbc-wrapper/blob/release/next/src/main/java/com/ing/data/cassandra/jdbc/CassandraDriver.java#L54)

**Comment by maximevw** [comment]
You're right. I add this in my todo list to fix this with an "elegant" solution centralizing the version at only one place to easily propagate any change anywhere it's necessary.

**Comment by sualeh** [comment]
Thanks for fixing
