### ISSUE TITLE
NullPointerException getting types

### ISSUE THREAD

**Issue by sualeh** [ing-bank/cassandra-jdbc-wrapper#38]
In [TypeMetadataResultSetBuilder::buildUDTs](https://github.com/ing-bank/cassandra-jdbc-wrapper/blob/release/next/src/main/java/com/ing/data/cassandra/jdbc/metadata/TypeMetadataResultSetBuilder.java#L119), `typeNamePattern` needs a null-check. Most JDBC drivers support a null `typeNamePattern` even though the JDBC javadoc does not specifically call out this case.

It is easy enough to use:
`if (typeNamePattern != null && typeNamePattern.contains(".")) {` on line L119.

**Comment by maximevw** [comment]
Hello @sualeh, good catch!

We can even handle null type name patterns as equivalent of the pattern "%" to match any type by replacing the lines 118-119 by:
```java
final AtomicReference<String> typeName = new AtomicReference<>(Objects.toString(typeNamePattern, "%"));
if (typeName.get().contains(".")) {
```

This also will avoid to get NPE later line 130 when the type name pattern is used to be matched against the found UDTs.

I'll take care of this one and keep you informed.

**Comment by maximevw** [comment]
Fixed and tested in commit https://github.com/ing-bank/cassandra-jdbc-wrapper/commit/eeea9a7da4c75894c47231c66783f5aa730a1e6a
