### ISSUE TITLE
Handle multiple host:port in the JDBC connection string

### ISSUE THREAD

**Issue by maximevw** [ing-bank/cassandra-jdbc-wrapper#41]
### Discussed in https://github.com/ing-bank/cassandra-jdbc-wrapper/discussions/40

<div type='discussions-op-text'>

<sup>Originally posted by **stefanofornari** November 13, 2023</sup>
Hello, it is mentioned several time the connection string is something like:

jdbc:cassandra://host1--host2--host3:9042/keyspace

What if nodes have different ports? can the below be used?

jdbc:cassandra://host1:port1--host2:port2--host3:port3/keyspace

</div>

**Comment by stefanofornari** [comment]
Do you think it is a candidate for next release? If you give me some directions I can maybe help (integration test aside :) )

**Comment by sualeh** [comment]
@maximevw Suggestion: 

Instead of:

jdbc:cassandra://host1:port1--host2:port2--host3:port3/keyspace

how about keeping the host:port convention standard, and allowing the other hosts to be specified in connection properties - for example:

jdbc:cassandra://host1:port1/keyspace?hosts=host2:port2--host3:port3

**Comment by stefanofornari** [comment]
Alternatively, on the line of @sualeh's comment:

jdbc:cassandra://host1:port1;host2:port2;host3:port3.../keyspace

**Comment by maximevw** [comment]
Thank you both @stefanofornari and @sualeh for your sugggestions.

I prefer the syntax originally suggested: jdbc:cassandra://host1:port1--host2:port2.../keyspace.

Why?

For now, keeping the separator "--" originally used will avoid to introduce a breaking change for users already using the syntax "host1--host2:port". Using "," or ";" as separator could be a good idea too, but I suggest to keep the current syntax, at least for short term.

Separating the additional contact points in a dedicated parameter could be a solution, but it splits the information in two places and IMHO, it makes it less readable. Moreover, it doesn't make sense to separate a particular contact point from the others (given how Cassandra works). I prefer to keep them together. Also, I remembered, for example, the syntax used by PostgreSQL JDBC driver for fail-over is: "host:port, host:port, ..." (see [connection fail-over documentation](https://jdbc.postgresql.org/documentation/use/#connection-fail-over)). Note, other drivers do the same, like [multiple hosts with MySQL](https://dev.mysql.com/doc/connectors/en/connector-j-reference-jdbc-url-format.html). Consequently, I think it's better to keep all the hosts at the same place in the URL.

**Comment by sualeh** [comment]
@maximevw Thanks for the links. There seems to be some precedent for doing it the way you suggest that I was not aware of. I guess we should think of this as a connection string, rather than as a "connection URL" as JDBC tries to think of it.

**Comment by maximevw** [comment]
Implemented as discussed, by commit https://github.com/ing-bank/cassandra-jdbc-wrapper/commit/553010a3c4b4a4c54146b85db61ee3bb77dc0e0a.
Documentation updated here with examples of valid JDBC URLs: [JDBC wrapper usage](https://github.com/ing-bank/cassandra-jdbc-wrapper#usage)
This feature will be available in the next release (4.11.0).

Thanks again @stefanofornari for pointing out this particular case.

**Comment by stefanofornari** [comment]
Great job! Well, thanks to you for such good piece of software and to promptly address issues!
