### ISSUE TITLE
Wrong return count in executeBatch()

### ISSUE THREAD

**Issue by stefanofornari** [ing-bank/cassandra-jdbc-wrapper#63]
The current implementation of `executeBatch()` returns a wrong number of effected rows given the underlying driver does not provide such information. In the line below, `rowCounts[]` is updated with 1 for each statement in batch:

https://github.com/ing-bank/cassandra-jdbc-wrapper/blob/3ab76c07bf043cf93670b636452e0b4de53af29c/src/main/java/com/ing/data/cassandra/jdbc/CassandraPreparedStatement.java#L282

Accordingly to [`executeBatch()`](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#executeBatch--) javadoc it should be updated with SUCCESS_NO_INFO.

**Comment by maximevw** [comment]
Good catch @stefanofornari, I'll fix this asap.

**Comment by maximevw** [comment]
Will be fixed in the next release (see commit https://github.com/ing-bank/cassandra-jdbc-wrapper/commit/40f81093875331c967026c1de4fd2dbf5bc31219).
