### ISSUE TITLE
Return all supported properties from CassandraDriver.getPropertyInfo

### ISSUE THREAD

**Issue by kornilova203** [ing-bank/cassandra-jdbc-wrapper#66]
DB tools like DataGrip use `Driver.getPropertyInfo` to display all possible connection parameters to user. Without this it's tricky for users to figure out what parameters are supported for driver.
There is a number of supported parameters in `SessionHolder.createSession` but they are not returned from `Driver.getPropertyInfo`

**Comment by maximevw** [comment]
This will be integrated to the next release.

**Comment by kornilova203** [comment]
Cool! Thanks
