### ISSUE TITLE
Can't set complianceMode="Liquibase" when create CassandraDataSource for cassandra-liquibase extension

### ISSUE THREAD

**Issue by Danil9966** [ing-bank/cassandra-jdbc-wrapper#68]
Currently i'm using cassandra-jdbc-wrapper 4.12.0 and cassandra-liquibase 4.28.0. DefaultOptionSet always returns 0 in getSQLUpdateResponse() method and to avoid such behaviour i've been told to use compliancemode=Liquibase parameter in connection url.  https://github.com/liquibase/liquibase-cassandra/issues/212#issuecomment-2199922649
it would be helpful to have this, because it just doesnt work otherwise, if we configure liquibase inside java app

**Comment by Danil9966** [comment]
pr opened

**Comment by maximevw** [comment]
> pr opened

I'll take a look at it as soon as possible. 🙂

**Comment by maximevw** [comment]
Fixed by #69
