### ISSUE TITLE
CassandraConnection.toString() leaks the password

### ISSUE THREAD

**Issue by ber00000** [ing-bank/cassandra-jdbc-wrapper#71]
Hi,

I'm using this library with [HikariCP](https://github.com/brettwooldridge/HikariCP) and I noticed that when Hikari add a connection to the pool, the connection properties are logged including the password in clear text!

Passwords should not leak.

It can simply be reproduced by this snippet:
```java
final Connection connection = DriverManager.getConnection(url, user, password);
System.out.println("connection = " + connection);
```

It will print out something like this:

`
connection = CassandraConnection [connectionProperties=... password=password, ..., user=user ...}]
`

For comparison Oracle driver prints out:

`
connection oracle.jdbc.driver.T4CConnection@1b90bf7d
`

**Comment by maximevw** [comment]
Thanks @ber00000 for this finding!

A patched version 4.13.1 solving this issue has been published.
