### ISSUE TITLE
CodecNotFoundException

### ISSUE THREAD

**Issue by codingsxx** [ing-bank/cassandra-jdbc-wrapper#75]
Was able to connect. Having issues with more complex data types such as List<Frozen<Map<TEXT, TEXT>>> or List<Frozen<Map<TEXT, List<Frozen<Map<TEXT, TEXT>>>>>> where it maps to java.lang.String

**Comment by maximevw** [comment]
A fix will be provided in the next release (4.14.0). See cc0f152.
